### ISSUE TITLE
Overview Endpoint

### ISSUE THREAD

**Issue by TheScree** [MalekaiProject/malekaiAPI#18]
api/overview would be a combination of the Videos (10 entries), News (10 entries), Devtracker (20 entries), and Changelog (50 entries) endpoints. This would be used to construct the new front page layout. An array of the four data collections would be returned, each formatted as if retrieving their respective endpoints.

Should help reduce needing 4 API calls for each loading of the front page.

**Comment by tylerdmace** [comment]
You're trading four smaller calls (which can be done asynchronously) for one large call. For overviews/dashboards, I always recommend making asynchronous calls for smaller, more atomic data, and then display the data as soon as it comes back. That way you aren't waiting for all data before you can render anything which makes for a smoother UX.

**Comment by TheScree** [comment]
Hrmmm, interesting. That's as close to a best practice I've been able to find yet. I had thought that making less calls to an API would reduce pressure on the API from a volume standpoint. I can see either side.

**Comment by tylerdmace** [comment]
Generally speaking the API is not gonna be your bottleneck; you will run into front-side issues well before you have saturated things on the back-end.

**Comment by TheScree** [comment]
Okay, so with that approach, this issue won't be needed but issues #17 #14 #13 will be needed in their place.
